spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://lxp-mysql:3306/lxp_recommend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false

  data:
    redis:
      host: redis
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
# Cloudflare R2 (.env 환경변수 참조)
r2:
  endpoint: ${R2_ENDPOINT_URL}
  access-key: ${R2_ACCESS_KEY_ID}
  secret-key: ${R2_SECRET_ACCESS_KEY}
  bucket: ${R2_BUCKET_NAME}
  region: ${R2_REGION:auto}

# 도메인 바꾸기
engine:
  callback-url: http://localhost:8085/internal/sync

passport:
  key:
    secret-key: ${PASSPORT_SECRET}

logging:
  level:
    com.lxp.recommend: DEBUG
    org.hibernate.SQL: DEBUG
